### ISSUE TITLE
Incorrect example for REL::VariantOffset in wiki

### ISSUE THREAD

**Issue by miere43** [CharmedBaryon/CommonLibSSE-NG#16]
[This wiki article](https://github.com/CharmedBaryon/CommonLibSSE-NG/wiki/Runtime-Targeting#relvariantoffset) contains following text:

> REL::VariantOffset
>
> Similar to REL::Offset, but with different offsets for SE, AE, and VR. This class is constructed with three arguments representing those three offsets. The first argument is the SE offset, the second is the AE offset, and the third is the VR offset. The correct offset is determined at the time the offset value is requested from the object.
> 
> This class can be passed directly to REL::Relocation in place of the regular REL::Offset, both when used as the sole argument or when used as the second argument following an ID.
> 
> REL::Relocation<int(int)> CallGetSystemMetrics(REL::RelocationID(36547, 35548), REL::VariantOffset(0xA9, 0x8A));

However, code example above would not compile because
1. `REL::Relocation` doesn't have constructor accepting `REL::VariantOffset` as second argument.
2. `REL::VariantOffset` doesn't have constructor acceping two arguments.

I guess it should be something like this?

```cpp
REL::Relocation<int(int)> CallGetSystemMetrics(REL::RelocationID(36547, 35548), REL::VariantOffset(0xA9, 0x8A, 0xA9).offset());
```

> This class can be passed directly to REL::Relocation in place of the regular REL::Offset, both when used as the sole argument or when used as the second argument following an ID.

This text is also wrong, because `REL::Relocation` doesn't accept `REL::Offset` in constructors.

**Comment by jpstewart** [comment]
Updated example to use three arguments. I will leave the part about it being passable directly to `REL::Relocation` because the fix for that is already on a branch and expected to be merged today, but I will leave the issue open until the PR is completed.

**Comment by jpstewart** [comment]
Merged the fix.
