### ISSUE TITLE
Invalid vfunction address in CROSS_VR version of NiAVObject

### ISSUE THREAD

**Issue by Acro748** [CharmedBaryon/CommonLibSSE-NG#50]
for explain
void PerformOp(PerformOpFunc& a_func) is located in 0x26 of the vtable on SE&AE and located in 0x27 of the vtable on VR

but in NiAVObject.cpp
it's defined 0x03 on SE&VR and 0x04 on VR

as such this, all NiAVObject vfunctions in the SKYRIM_CROSS_VR version define an invalid address

**Comment by jpstewart** [comment]
I will be looking into this by Monday (7-11-22) and if a fix is needed will try to push one out to the Vcpkg repo within a day.

**Comment by jpstewart** [comment]
Fix is now on `main`, will be in the upcoming release.
