### ISSUE TITLE
AddEventSink<RE::BGSActorCellEvent> sends Skyrim into infinite loop in 3.5.6

### ISSUE THREAD

**Issue by eddoursul** [CharmedBaryon/CommonLibSSE-NG#56]
I had successfully built [Artifact Tracker](https://eddoursul.win/mods/artifact-tracker/) for 1.5.97-1.6.353 before, but since one of the latest updates an ordinary call
```
RE::PlayerCharacter::GetSingleton()->AddEventSink<RE::BGSActorCellEvent>(EventListener::GetSingleton());
```
sends Skyrim into infinite loop in all runtimes.

I made a demo of this issue, containing only this call and nothing else:
https://github.com/eddoursul/ng-infinite-loop/blob/master/src/Main.cpp#L32

**Comment by jpstewart** [comment]
Should be fixed now.
