### ISSUE TITLE
`PlayerCharacter::HasActorDoingCommand()` behaves differently pre- and post-1.6.629

### ISSUE THREAD

**Issue by WaterFace** [CharmedBaryon/CommonLibSSE-NG#57]
The function seems to always return `true` in versions 1.6.629+. Replacing `playerCharacter->HasActorDoingCommand()` with `static_cast<bool>(playerCharacter->GetActorDoingPlayerCommand())` (which was the implementation prior to 61383c799cf5b408af2e3bb4e93d2eb74d65b6dd) seems to give the correct result. Tested on 1.6.353 and 1.6.640.

**Comment by jpstewart** [comment]
Now fixed.
