### ISSUE TITLE
Provide a way in CMAKE to add a static plugin library

### ISSUE THREAD

**Issue by panic-sell** [CharmedBaryon/CommonLibSSE-NG#80]
Right now `add_commonlibsse_plugin()` creates a shared library, which makes unit testing cumbersome because we have to export all the to-be-tested classes/functions. We also have to worry about DLL boundary quirks when writing tests.

Being able to statically link tests with plugin code would make things a lot less painful.

**Comment by jpstewart** [comment]
This is supported by using the following style instead of `add_commonlibsse_plugin`:

```cmake
add_library(MyPlugin STATIC Main.cpp)

target_commonlibsse_properties(MyPlugin)
```
